owner: cantorgymnasium
repo: status

sites:
  - name: Gitea
    url: https://git.cantorgymnasium.de
  - name: mailcow UI
    url: https://mail.cantorgymnasium.de
  - name: Seafile
    url: https://cloud.cantorgymnasium.de
  - name: GCG.Website
    url: https://cantorgymnasium.de/

status-website:
  cname: status.cantorgymnasium.de
  logoUrl: https://git.cantorgymnasium.de/gcg/gcg-website/raw/branch/master/static/media/logo_sm_yellow.svg
  name: GCG.IT Monitoring
  introTitle: "Status - IT am GCG"
  introMessage: Hier wird der Status der internen und öffentlichen Dienste am GCG angezeigt.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
