owner: cantorgymnasium
repo: status

sites:
  - name: Gitea
    url: https://git.cantorgymnasium.de/
  - name: mailcow UI
    url: https://mail.cantorgymnasium.de/
  - name: SOGo Webmail
    url: https://mail.cantorgymnasium.de/SOGo/
  - name: Nextcloud
    url: https://cloud.cantorgymnasium.de/
  - name: Nextcloud AIO Interface
    url: https://nc-admin.cantorgymnasium.de/
  - name: GCG.Website
    url: https://cantorgymnasium.de/
  - name: GCG.Website (Test)
    url: https://test.cantorgymnasium.de/
  - name: GCG.Website (Dev)
    url: https://dev.cantorgymnasium.de/
  - name: Grafana
    url: https://grafana.cantorgymnasium.de/
  - name: HedgeDoc
    url: https://pads.cantorgymnasium.de/
  - name: Keycloak
    url: https://id.cantorgymnasium.de/
  - name: Matomo
    url: https://analytics.cantorgymnasium.de/
  - name: POSTalion
    url: https://forms.cantorgymnasium.de/status
  - name: Portainer
    url: http://docker.cantorgymnasium.de:9000/
  #- name: GLPI
  #  url: https://glpi.cantorgymnasium.de/index.php?error=1
  - name: WikiJS
    url: https://wiki.cantorgymnasium.de/
  - name: Homer Dashboard
    url: https://dash.cantorgymnasium.de/
  - name: Webmin
    url: https://webmin.cantorgymnasium.de:10000/
    __dangerous__insecure: true
  - name: DBGate
    url: https://db.cantorgymnasium.de/
  - name: Schülerzeitung
    url: https://schuelerzeitung-gcg.de/
  - name: Schuelerzeitung (Test)
    url: https://test.schuelerzeitung-gcg.de/
  - name: Marzipano
    url: https://vr.cantorgymnasium.de/

assignees:
  - denyskon
  - Tramus00

status-website:
  cname: status.cantorgymnasium.de
  logoUrl: https://git.cantorgymnasium.de/gcg/gcg-website/raw/branch/master/static/media/logo_sm_yellow.svg
  name: GCG.IT Monitoring
  introTitle: "Status - IT am GCG"
  introMessage: Hier wird der Status der internen und öffentlichen Dienste am GCG angezeigt.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: GCG.Website
      href: https://cantorgymnasium.de/
    - title: Portainer
      href: https://docker.cantorgymnasium.de/
    - title: Webmin
      href: https://webmin.cantorgymnasium.de:10000/
